### PR TITLE
Proposed Changes

### PR DESCRIPTION
**Pull request by cvburgess**

### CODE REVIEW

**Comment by cvburgess** [comment]
@eriqbre some alternate naming for category:

```js
category: {
    categoryID: "001010100101",
    groupID: 6,
    label: "Poultry"
}
```

**Comment by eriqbre** [comment]
i'm fine with categoryId and label but I don't think i agree on group, this isn't a group, it's technically the top level of CMIM which is called the "category". if we imagine that other consumers of this data will have the frame of reference of CMIM and how each level is defined then I think we need to stay consistent. 

as for opco, that's required as part of the primary key for TW so we'll need to keep the top level parameter, i'm good with all the other changes

**Comment by cvburgess** [comment]
Gotcha @eriqbre - i used group because Brett gave us an earful on how Sysco wanted to always refer o that as the group not "category" - ill rework without that notion

**Comment by cvburgess** [comment]
@eriqbre the current code (not the alternate options don't use the word group - check the diff in "Files Changed" above

**Pull request merged**
